"""
Generate intent classification training data for FundPilot router.

4 intents:
  overlap   — user asks about holdings overlap between ETFs
  compare   — user wants a side-by-side comparison of two ETFs
  portfolio — user asks about overall portfolio / allocation
  ask       — general question (price, trend, news, etc.)

Run:
    python tools/generate_training_data.py
Outputs:
    data/intent_train.jsonl
    data/intent_test.jsonl
"""
from __future__ import annotations

import json
import random
from pathlib import Path

random.seed(42)

# ── Raw examples per intent ────────────────────────────────────────────────────

OVERLAP: list[str] = [
    "VUAG和CSP1有多少持仓重叠？",
    "这两只ETF持仓重复度高吗？",
    "SWDA和VWRP有没有重叠成分股？",
    "我watchlist里有哪些ETF持仓雷同？",
    "帮我看看这些ETF有没有重合的股票",
    "HMWS和VWRL的持仓是否相同？",
    "这几只ETF重叠严重吗？",
    "有哪些ETF和VUAG持仓一样？",
    "检查一下ETF之间的重复度",
    "SWDA跟VWRP持仓一样吗",
    "我持有的这些基金有没有重叠部分？",
    "分析一下我的watchlist里各ETF之间的持仓重合情况",
    "CSP1和VUAG有多少共同持仓？",
    "这两个ETF是不是买了一样的股票？",
    "我想知道持仓重叠率",
    "这些ETF的成分股有没有重复的？",
    "告诉我哪些基金持仓雷同，可以缩减",
    "VUAG和VWRL有没有overlap？",
    "overlap analysis for SWDA and VUAG",
    "do SWDA and VWRP overlap in holdings?",
    "what is the overlap between CSP1 and VUAG?",
    "check for duplicate holdings across my watchlist",
    "any redundant ETFs in my list?",
    "which ETFs share the same stocks?",
    "holdings overlap between HMWS and VWRL please",
    "VWRP和SWDA持仓有重合吗？",
    "我的基金会不会有重复持仓",
    "帮我分析一下持仓有没有雷同的地方",
    "这两只基金是不是在买同样的东西？",
    "基金重叠分析",
    "帮我查一下重叠",
    "有没有重叠持仓的问题？",
    "这两个ETF里面有没有一样的股票？",
    "我买的几个ETF是不是有很多相同的成分股？",
    "VUAG SWDA overlap有多少？",
    "比较一下持仓是否重复",
    "持仓重叠高不高？",
    "哪些ETF可以因为重叠而合并？",
    "我需要了解我的ETF持仓有没有重复投资的情况",
    "有哪些ETF可以替代掉，因为它们和另一个持仓很像？",
    "你能告诉我我的watchlist里哪些基金在持仓上非常相似吗？",
    "SWDA 和 VWRP 有多少股票是一样的？",
    "分析一下 watchlist 中各基金重叠情况",
    "这几个ETF的持仓有多少比例是一样的？",
    "我想看看我买的这些ETF有没有冗余",
    "CSP1 VUAG 哪两个重叠最多？",
    "帮我查ETF之间的股票重合率",
    "我的基金持仓里有没有重叠买了同一只股票？",
    "有没有overlap的问题？",
    "我的基金里有没有重叠持仓问题？",
    "这些ETF彼此之间是不是有很多重叠？",
    "有没有哪两个ETF基本上一样，可以精简掉一个？",
    "请检查持仓雷同情况",
    "我这几个基金有没有持仓上的重复？",
    "HMWS和VWRP差别大吗，还是大部分持仓一样？",
    "两个ETF的重叠率是多少？",
    "请帮我分析我的watchlist中ETF的重合程度",
    "CSP1 和 SWDA 里面有没有同样的公司？",
    "想了解我的ETF是否有重叠投资",
    "VUAG CSP1 overlap analysis",
    "tell me which ETFs are redundant due to overlap",
    "check overlap between VWRP and SWDA",
    "are there overlapping holdings in my portfolio?",
    "find duplicate stocks across my ETFs",
    "SWDA vs VWRP holdings overlap",
    "how much do VUAG and CSP1 overlap?",
    "is there significant overlap between my ETFs?",
    "show me overlap between all ETFs",
    "which funds have the most holdings in common?",
    "identify redundant ETFs based on overlap",
    "these ETFs seem to hold the same stocks",
    "check for redundancy in my watchlist",
    "my ETFs probably overlap — can you check?",
    "do I have overlapping positions?",
    "is buying both VUAG and CSP1 redundant?",
    "are CSP1 and SWDA basically the same ETF?",
    "VWRL和VWRP都是一样的吗？",
    "这两个会不会持仓高度重叠？",
    "我买了重复的ETF吗？",
    "帮我看看有没有买了差不多东西的ETF",
    "检查一下有没有重叠",
    "持仓重合分析",
    "重叠度分析",
    "有没有买了差不多的两只基金",
    "基金成分是否雷同？",
    "我的基金持仓高度重叠吗",
    "持仓有重复吗",
    "这些ETF是不是有大量重复的持仓？",
    "基金重叠度多少",
    "你觉得我有没有持仓重复的问题",
    "我的ETF是否存在重复投资",
    "有没有ETF之间持仓非常接近？",
    "成分股重叠情况",
    "你能帮我看看这几个基金是不是有很多重叠吗？",
    "SWDA VUAG哪些股票重复了？",
    "tell me about holdings redundancy",
    "overlap check please",
    "are my ETF holdings overlapping?",
    "I want to see the overlap analysis",
    "check which ETFs have similar holdings",
    "VUAG and CSP1 seem similar, how much do they overlap?",
]

COMPARE: list[str] = [
    "VUAG和VWRP哪个更好？",
    "对比一下SWDA和VWRL",
    "CSP1 vs VUAG有什么区别？",
    "HMWS和SWDA比较",
    "比较一下VWRP和VUAG",
    "VUAG和CSP1哪只更适合长期持有？",
    "SWDA和VWRL在费率上有什么差异？",
    "给我比较一下VUAG和CSP1的优劣",
    "这两只ETF有什么区别？",
    "VWRP和VWRL哪个分红更好？",
    "帮我对比SWDA和HMWS",
    "compare VUAG and CSP1",
    "what is the difference between SWDA and VWRL?",
    "VUAG vs CSP1 which is better?",
    "compare HMWS and SWDA for me",
    "VWRP vs VWRL differences",
    "which is better, VUAG or SWDA?",
    "side by side comparison of CSP1 and VUAG",
    "compare the two ETFs",
    "how does SWDA compare to VWRL?",
    "VUAG和CSP1的TER哪个低？",
    "SWDA和VWRL追踪的指数有什么不同？",
    "比较一下HMWS和VWRP的规模",
    "VWRL和VWRP有什么区别？",
    "对比这两只ETF的费用",
    "VUAG CSP1 哪个更好",
    "SWDA 和 VWRL 我应该买哪个？",
    "这两个ETF优劣势分别是什么？",
    "分析一下VUAG和CSP1的差异",
    "HMWS 和 SWDA 哪只适合我？",
    "CSP1 VUAG 对比分析",
    "帮我对比两只ETF",
    "比较一下两只基金的费率",
    "哪个ETF追踪的指数更好？",
    "我应该选VWRP还是VWRL？",
    "比较这两只ETF的表现",
    "帮我比较SWDA和VWRL的投资区域",
    "VUAG是积累型吗，和VWRL哪个好？",
    "SWDA和CSP1指数有什么区别？",
    "我想了解HMWS和VWRP的区别",
    "对比两个ETF的持仓风格",
    "VUAG和SWDA哪个覆盖市场更广？",
    "帮我分析VWRL和VWRP的差异",
    "CSP1 VUAG 优劣对比",
    "这两只ETF哪只风险更低？",
    "compare VWRP and VUAG for income vs growth",
    "SWDA or VWRL for long term?",
    "which ETF has lower fees, CSP1 or VUAG?",
    "difference between accumulating and distributing ETF",
    "VUAG vs SWDA global coverage comparison",
    "help me choose between CSP1 and VUAG",
    "is SWDA better than VWRL?",
    "HMWS vs SWDA which is more diversified?",
    "compare TER of VWRP and VWRL",
    "what are the key differences between these two ETFs?",
    "SWDA VWRL 哪个好？",
    "CSP1还是VUAG？",
    "这两个ETF哪个值得买",
    "帮我分析这两只的区别",
    "比一比SWDA和CSP1",
    "VWRP 和 VWRL 哪个派息更多？",
    "两只ETF规模有区别吗？",
    "哪个ETF覆盖范围更大？",
    "这两个基金费率哪个低？",
    "比较一下这两只ETF的涨跌情况",
    "SWDA和VUAG追踪同一个指数吗？",
    "HMWS的风险和SWDA比怎么样？",
    "VUAG是否比CSP1更分散？",
    "比较VWRL和VWRP的历史表现",
    "CSP1和VUAG哪个适合美股敞口？",
    "这两只哪个更适合我的投资风格？",
    "对比CSP1和SWDA的行业暴露",
    "请比较VWRP和HMWS",
    "SWDA vs VUAG区别是什么？",
    "和我对比分析一下这两只ETF",
    "give me a comparison between VUAG and VWRP",
    "compare SWDA and CSP1 side by side",
    "which has better returns, VWRL or VWRP?",
    "VUAG vs VWRL comparison",
    "HMWS versus SWDA comparison",
    "difference between CSP1 and SWDA index",
    "compare market cap coverage of VUAG and VWRL",
    "SWDA vs VWRP for a long-term investor",
    "compare distribution policy of VWRL and VWRP",
    "VUAG or CSP1 for US market exposure?",
    "which ETF is better for emerging markets?",
    "help me decide between SWDA and VWRL",
]

PORTFOLIO: list[str] = [
    "帮我分析一下整体组合",
    "我的ETF组合怎么样？",
    "分析一下我整个watchlist",
    "我的portfolio配置合理吗？",
    "我的投资组合有哪些风险？",
    "帮我看看整体仓位",
    "我的所有ETF加起来曝险如何？",
    "分析一下全部ETF的整体情况",
    "portfolio分析",
    "我现在的配置怎么样？",
    "帮我看看整体资产配置",
    "我的ETF组合是否过于集中？",
    "我的投资组合覆盖哪些市场？",
    "整体配置分析",
    "看一下我全部的ETF",
    "分析我的整体持仓情况",
    "我的watchlist整体风险高吗？",
    "帮我分析整体的暴露区域",
    "我持有的所有ETF组合情况",
    "分析所有基金的总体配置",
    "portfolio analysis please",
    "analyze my overall ETF portfolio",
    "how is my portfolio diversified?",
    "what is my total market exposure?",
    "give me an overview of my portfolio",
    "portfolio risk assessment",
    "analyze all ETFs in my watchlist",
    "how concentrated is my portfolio?",
    "overall portfolio allocation",
    "what regions does my portfolio cover?",
    "我的组合配置是否均衡？",
    "整个组合的行业分布怎么样？",
    "我持有的ETF在地区上是否过于集中？",
    "帮我查看整体组合的集中度",
    "我的ETF总体分散效果如何？",
    "整体持仓分析",
    "我买的这些ETF加在一起覆盖范围够广吗？",
    "我的投资组合是否合理？",
    "总体ETF组合分析",
    "我的所有基金加起来是什么样的配置？",
    "帮我看看我的整个组合",
    "我的ETF组合是否需要调整？",
    "portfolio怎么样",
    "整体情况怎么样",
    "我的仓位集中在哪里？",
    "我的基金配置情况",
    "分析整个watchlist的配置",
    "我的投资组合有没有EM敞口？",
    "check my portfolio composition",
    "portfolio breakdown please",
    "how is my total exposure looking?",
    "show me a portfolio analysis",
    "my overall ETF allocation",
    "is my portfolio balanced?",
    "what sector exposure does my portfolio have?",
    "analyze the composition of my watchlist",
    "give me a full portfolio breakdown",
    "how diversified am I across regions?",
    "我的整个基金组合风险怎么样",
    "帮我分析下整体的资产配置",
    "我的组合里有没有冗余仓位",
    "整体组合我是否过于集中美股？",
    "我的全部ETF配置是否分散？",
    "组合整体来说有什么问题？",
    "我的基金组合结构是什么样的？",
    "所有ETF加在一起总体配置情况",
    "帮我评估一下我的投资组合",
    "我的组合有哪些缺口？",
    "我的ETF覆盖了哪些地区？",
    "分析一下我的整体ETF布局",
    "我的ETF是否存在风格偏差？",
    "组合里有没有太多成长股ETF？",
    "total exposure analysis",
    "what does my portfolio look like overall?",
    "portfolio health check",
    "assess my entire watchlist",
    "what is missing from my portfolio?",
    "regional concentration in my portfolio",
    "am I overexposed to any single market?",
    "full portfolio review",
    "allocation overview for all my ETFs",
    "is my portfolio too US-heavy?",
    "how much EM exposure do I have?",
    "check the style tilt of my portfolio",
    "summarize my portfolio",
    "overview of my holdings",
    "what does my overall allocation look like?",
    "整体来看我的基金配置有没有问题",
    "我的组合整体风险敞口",
    "我的ETF组合风格偏成长还是价值？",
    "帮我做一个portfolio review",
    "组合里有没有太多重叠的ETF？",
    "我的portfolio是否需要再平衡？",
    "帮我看看我的所有ETF",
]

ASK: list[str] = [
    "VUAG今天的价格是多少？",
    "CSP1最近表现怎么样？",
    "SWDA今天涨了吗？",
    "市场整体情况怎么样？",
    "HMWS最新净值多少？",
    "今天有什么异动吗？",
    "VWRP的价格是多少？",
    "今日市场有什么值得关注的？",
    "ETF今天有没有大涨大跌？",
    "告诉我一下最新行情",
    "VUAG现在多少钱？",
    "给我看看今天的市场数据",
    "SWDA有没有触发警报？",
    "最近有什么需要关注的？",
    "今天市场表现如何？",
    "VWRL有什么异动吗？",
    "CSP1的20日均线在哪里？",
    "给我最新的价格数据",
    "今天有什么需要注意的吗？",
    "HMWS最近一个月走势如何？",
    "what is the price of VUAG today?",
    "how did CSP1 perform recently?",
    "is SWDA up or down today?",
    "what is the current market situation?",
    "show me today's market data",
    "any notable moves in the watchlist?",
    "latest price for VWRP?",
    "what should I watch out for today?",
    "has anything triggered an alert?",
    "give me the latest market update",
    "VUAG最近三个月怎么样？",
    "告诉我今天的涨跌",
    "今天市场有什么新闻吗？",
    "SWDA的成交量怎么样？",
    "市场现在是熊市还是牛市？",
    "今天有什么异常波动吗？",
    "最新行情如何？",
    "帮我看看今天的价格",
    "HMWS今天涨跌幅多少？",
    "今天需要关注哪些ETF？",
    "告诉我VUAG最新价格",
    "今天美股怎么样",
    "欧洲市场表现如何",
    "我的watchlist里今天有没有大变动",
    "告诉我一下最近的行情",
    "最近市场怎么样",
    "今天有触发什么警报吗",
    "有没有什么ETF今天暴涨或暴跌",
    "帮我看一下今天的数据",
    "最近有什么大事吗",
    "what happened in the market today?",
    "any big moves today?",
    "check VUAG price",
    "what is SWDA trading at?",
    "market update please",
    "how is HMWS doing?",
    "any alerts triggered today?",
    "show me the latest data",
    "what are the latest prices?",
    "any significant market moves?",
    "tell me about today's market",
    "current price of CSP1",
    "VWRL performance today",
    "what is SWDA's 20-day moving average?",
    "is the market bullish or bearish?",
    "any big drops or gains in my watchlist?",
    "what should I be watching today?",
    "latest market news?",
    "how is my watchlist doing overall?",
    "show me recent performance",
    "market summary for today",
    "VUAG price trend",
    "VWRP今天怎么样",
    "告诉我今天ETF行情",
    "CSP1最新价格",
    "我的ETF今天有没有大变动",
    "有没有什么警报",
    "今天有没有需要操作的",
    "市场现在怎么样",
    "告诉我当前的市场状况",
    "今天有没有跌很多的ETF",
    "帮我看看行情",
    "ETF最新行情",
    "今天涨跌如何",
    "目前市场整体情况",
    "今天SWDA表现如何",
    "最近VWRP有什么异动吗",
    "给我一个市场简报",
    "今日行情摘要",
    "有没有触发技术指标信号",
    "今天的市场数据怎么样",
    "HMWS现在多少价格",
    "VWRL今日价格",
    "今天需要做什么操作吗",
    "市场有没有什么异常",
    "我的ETF最新情况",
    "今天有没有大的市场波动",
    "give me a quick market check",
    "quick update on my watchlist",
    "VUAG latest",
    "CSP1 today",
    "anything happening in the market?",
    "monitor status",
    "prices for today",
    "what's the latest?",
    "any notable movements?",
    "how are things looking?",
]

# ── Build dataset ──────────────────────────────────────────────────────────────

def build_dataset() -> list[dict]:
    examples = []
    for text in OVERLAP:
        examples.append({"text": text.strip(), "label": "overlap"})
    for text in COMPARE:
        examples.append({"text": text.strip(), "label": "compare"})
    for text in PORTFOLIO:
        examples.append({"text": text.strip(), "label": "portfolio"})
    for text in ASK:
        examples.append({"text": text.strip(), "label": "ask"})
    return examples


def main():
    data_dir = Path(__file__).resolve().parent.parent / "data"
    data_dir.mkdir(exist_ok=True)

    dataset = build_dataset()
    random.shuffle(dataset)

    split = int(len(dataset) * 0.85)
    train = dataset[:split]
    test  = dataset[split:]

    train_path = data_dir / "intent_train.jsonl"
    test_path  = data_dir / "intent_test.jsonl"

    with open(train_path, "w", encoding="utf-8") as f:
        for ex in train:
            f.write(json.dumps(ex, ensure_ascii=False) + "\n")

    with open(test_path, "w", encoding="utf-8") as f:
        for ex in test:
            f.write(json.dumps(ex, ensure_ascii=False) + "\n")

    label_counts: dict[str, int] = {}
    for ex in dataset:
        label_counts[ex["label"]] = label_counts.get(ex["label"], 0) + 1

    print(f"Total examples : {len(dataset)}")
    print(f"Train          : {len(train)}")
    print(f"Test           : {len(test)}")
    print("Label counts   :", label_counts)
    print(f"Saved → {train_path}")
    print(f"Saved → {test_path}")


if __name__ == "__main__":
    main()
